version: "3.9"
services:
    crypto-app:
        container_name: crypto-app
        restart: always
        image: mats9798/laravel8-php-8-apache:latest
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ${PROJECT_ROOT}:/var/www/html
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        hostname: cryptocademy.developer.local
        ports:
            - 9876:80
        networks:
            crypto-net:

    crypto-app_db:
        container_name: crypto-app_db
        image: mysql:8
        restart: always
        networks:
            crypto-net:
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cryptocademy
        volumes:
            - crypto_mysql_data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - crypto-app_db
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - PMA_ABSOLUTE_URI=http://pma.developer.local
            - PMA_HOST=crypto-app_db
            - PMA_VERBOSE=CryptoAcademy
            - UPLOAD_LIMIT=2500M
        networks:
            crypto-net:
        ports:
            - 9001:80
volumes:
    crypto_mysql_data:
        name: crypto_mysql_data

networks:
    crypto-net:
        name: crypto-net
        driver: bridge
        ipam:
            config:
                -   subnet: 172.23.0.0/24
