version: "3.9"
services:
    cryptocademy:
        container_name: cryptocademy
        restart: always
        image: cryptocademy:latest
        build:
            dockerfile: ../build/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www/html
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app
        depends_on:
            - database
        ports:
            - 9876:80
        networks:
            crypto-net:

    cryptocademy_scheduler:
        container_name: cryptocademy_scheduler
        restart: always
        image: registry.cryptocademy.app:5000/cryptocademy:latest
        volumes:
            - ./:/var/www/html
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            APP_ENV: local
            CONTAINER_ROLE: scheduler
        depends_on:
            - database

    crypto-app_db:
        container_name: crypto-app_db
        image: mysql:8
        restart: always
        networks:
            crypto-net:
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cryptocademy
        volumes:
            - crypto_mysql_data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - crypto-app_db
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - PMA_ABSOLUTE_URI=http://pma.developer.local
            - PMA_HOST=crypto-app_db
            - PMA_VERBOSE=CryptoAcademy
            - UPLOAD_LIMIT=2500M
        networks:
            crypto-net:
        ports:
            - 9001:80
    crypto-app_mailhog:
        restart: always
        image: mailhog/mailhog:latest
        container_name: crypto-app_mailhog
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        networks:
            crypto-net:
        ports:
            - 9002:8025
volumes:
    crypto_mysql_data:
        name: crypto_mysql_data

networks:
    crypto-net:
        name: crypto-net
        driver: bridge
        ipam:
            config:
                -   subnet: 172.23.0.0/24
