#!/bin/bash
echo_and_run() {
    echo "$*"
    "$@"
}
DOCKER_DIR=$(pwd)/docker/developer
PROJECT_ROOT=$(pwd)
echo "PROJECT_ROOT=$PROJECT_ROOT" >$DOCKER_DIR/.env

echo_and_run $(pwd)

echo_and_run docker-compose -f $DOCKER_DIR/docker-compose.yml pull
echo_and_run docker-compose -f $DOCKER_DIR/docker-compose.yml up -d --force-recreate
echo_and_run docker pull mats9798/crypto-app:latest
echo_and_run rm -rf $(pwd)/composer.lock

if [ ! -f $(pwd)/.env ]; then
    echo_and_run cp -ap $DOCKER_DIR/laravel.env $(pwd)/.env
fi

echo_and_run docker run --rm --interactive --tty -v $(pwd):/app -w /app -u $UID mats9798/crypto-app:latest composer update
echo_and_run docker run --rm --interactive --tty -v $(pwd):/app -w /app -u $UID mats9798/crypto-app:latest composer install --no-interaction --optimize-autoloader
echo_and_run docker run --rm --interactive --tty -v $(pwd):/app -w /app node:14 npm install

echo_and_run docker exec -it crypto-app chmod -R 777 ./storage
echo_and_run docker exec -it crypto-app chmod 777 ./.env
