<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class SymbolUserResource extends JsonResource
{
  public static function collection($resource)
  {
    self::withoutWrapping();
    return parent::collection($resource); // TODO: Change the autogenerated stub
  }
  /**
   * Transform the resource into an array.
   *
   * @param \Illuminate\Http\Request $request
   * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
   */

  public function toArray($request)
  {
    self::withoutWrapping();
    return [
      'id' => $this->id,
      'name' => $this->name,
      'symbol' => $this->api_symbol,
      'is_favorite' => $this->is_favorite,
    ];
  }
}
