<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class TransactionResource extends JsonResource
{
  public static function collection($resource)
  {
    self::withoutWrapping();
    return parent::collection($resource); // TODO: Change the autogenerated stub
  }

  /**
   * Transform the resource into an array.
   *
   * @param \Illuminate\Http\Request $request
   * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
   */

  public function toArray($request)
  {
    self::withoutWrapping();
    return [
      'quantity' => $this->quantity,
      'symbol' => $this->symbol,
      'api_symbol' => $this->api_symbol,
      'price' => $this->price,
      'action' => $this->action,
      'bought_at' => $this->created_at,
    ];
  }

}
