export const TimeFrame = {
  ONE_MONTH: "one_month",
  SIX_MONTHS: "six_months",
  ONE_YEAR: "one_year",
  ALL: "all",
};

export const ChartType = {
  AREA: "area",
  LINE: "line",
};

export const Coin = {
  BTC: "BTC",
  ETH: "ETH",
};

export const Dimension = {
  ONE_HOUR: "1H",
  ONE_DAY: "1D",
  ONE_WEEK: "1W",
  ONE_MONTH: "1M",
  ONE_YEAR: "1Y",
  ALL: "All",
};

export const AcademyCategory = {
  CRYPTO: "CRYPTO",
  TRADING: "TRADING",
  TOP_FIVE_COINS: "TOP_FIVE_COINS",
  FIFTY_COINS__LIST: "FIFTY_COINS__LIST",
  GLOSSAR__LIST: "GLOSSAR__LIST",
};

export const AcademyTopic = {
  CRYPTO__INTRO: "CRYPTO__INTRO",
  CRYPTO__INTRO__WALLETS: "CRYPTO__INTRO__WALLETS",
  CRYPTO__INTRO__SMART_CONTRACTS: "CRYPTO__INTRO__SMART_CONTRACTS",
  CRYPTO__BLOCKCHAIN: "CRYPTO__BLOCKCHAIN",
  CRYPTO__BLOCKCHAIN__TRANSACTIONS: "CRYPTO__BLOCKCHAIN__TRANSACTIONS",
  CRYPTO__BLOCKCHAIN__FEES: "CRYPTO__BLOCKCHAIN__FEES",
  CRYPTO__ADVANCED: "CRYPTO__ADVANCED",
  CRYPTO__ADVANCED__TRANSACTIONS: "CRYPTO__ADVANCED__TRANSACTIONS",
  CRYPTO__ADVANCED__MERKLETREE: "CRYPTO__ADVANCED__MERKLETREE",
  CRYPTO__ADVANCED__CONSENSUS: "CRYPTO__ADVANCED__CONSENSUS",
  CRYPTO__ADVANCED__PROOF_OF_WORK: "CRYPTO__ADVANCED__PROOF_OF_WORK",
  CRYPTO__ADVANCED__PROOF_OF_STAKE: "CRYPTO__ADVANCED__PROOF_OF_STAKE",
  TRADING__MARKET_ORDER: "TRADING__MARKET_ORDER",
  TRADING__LIMIT_ORDER: "TRADING__LIMIT_ORDER",
  TRADING__PRICE: "TRADING__PRICE",
  TRADING__AMM: "TRADING__AMM",
  TRADING__SLIPPAGE: "TRADING__SLIPPAGE",
  TRADING__TAXES: "TRADING__TAXES",
  TOP_FIVE_COINS__BTC: "TOP_FIVE_COINS__BTC",
  TOP_FIVE_COINS__ETH: "TOP_FIVE_COINS__ETH",
  TOP_FIVE_COINS__BNB: "TOP_FIVE_COINS__BNB",
  TOP_FIVE_COINS__USDT: "TOP_FIVE_COINS__USDT",
  TOP_FIVE_COINS__SOL: "TOP_FIVE_COINS__SOL",
};
