<?php

namespace App\Enum;

class MessageCodes
{
  const INSUFFICIENT_USER_BALANCE = "INSUFFICIENT_USER_BALANCE";
  const INSUFFICIENT_SYMBOL_AMOUNT = "INSUFFICIENT_SYMBOL_AMOUNT";

  const USER_DELETE = "USER_DELETE";
  const USER_RESET = "USER_RESET";
  const USER_NOT_FOUND = "USER_NOT_FOUND";
  const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
  const REGISTER_SUCCESS = "REGISTER_SUCCESS";
  const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
  const VERIFY_EMAIL_FAIL = "VERIFY_EMAIL_FAIL";
  const ACCOUNT_DOESNT_EXIST = "ACCOUNT_DOESNT_EXIST";
  const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";


  const ACCOUNT_ALREADY_VERIFIED = "ACCOUNT_ALREADY_VERIFIED";
  const USERDATA_CHANGE_SUCCESS = "USERDATA_CHANGE_SUCCESS";

  const SYMBOL_ALREADY_FAV = "SYMBOL_ALREADY_FAV";
  const SYMBOL_ISNOT_IN_FAV = "SYMBOL_ISNOT_IN_FAV";

  const PASSWORD_CHANGE_FAIL = "PASSWORD_CHANGE_FAIL";
  const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
}
