<?php

namespace App\Enum;

class MessageCodes
{
  const INSUFFICIENT_USER_BALANCE = 1;
  const INSUFFICIENT_SYMBOL_AMOUNT = 2;

  const USER_DELETE = 3;
  const USER_RESET = 4;
  const USER_NOT_FOUND = 5;
  const LOGOUT_SUCCESS = 6;
  const REGISTER_SUCCESS = 7;
  const VERIFY_EMAIL_SUCCESS = 8;
  const VERIFY_EMAIL_FAIL = 9;
  const ACCOUNT_DOESNT_EXIST = 10;
  const PASSWORD_RESET_SUCCESS = 11;
  const ACCOUNT_ALREADY_VERIFIED = 12;
  const PASSWORD_CHANGE_SUCCESS = 13;
  const USERDATA_CHANGE_SUCCESS = 14;

  const SYMBOL_ALREADY_FAV = 15;
  const SYMBOL_ISNOT_IN_FAV = 16;

}
