version: "3.9"
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        container_name: certbot
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    crypto-app:
        container_name: crypto-app
        restart: always
        image: mats9798/cryptocademy:latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - crypto_app_data:/var/www/html/storage
        environment:
            APP_ENV: production
            CONTAINER_ROLE: app
    scheduler:
        container_name: scheduler
        restart: always
        image: mats9798/cryptocademy:latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - crypto_app_data:/var/www/html/storage
        environment:
            APP_ENV: production
            CONTAINER_ROLE: scheduler

    crypto-app_db:
        container_name: crypto-app_db
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cryptocademy
            MYSQL_USER: cryptocademy
            MYSQL_PASSWORD: cryptocademy
        volumes:
            - crypto_mysql_data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - crypto-app_db
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - PMA_ABSOLUTE_URI=http://pma.developer.local
            - PMA_HOST=crypto-app_db
            - PMA_VERBOSE=CryptoAcademy
            - UPLOAD_LIMIT=2500M
        ports:
            - 8080:80
    mailhog:
        restart: always
        image: mailhog/mailhog:latest
        container_name: crypto-app_mailhog
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        ports:
            - 8025:8025
volumes:
    crypto_mysql_data:
        name: crypto_mysql_data
    crypto_app_data:
        name: crypto_app_data

networks:
    default:
        name: crypto-net
        driver: bridge
