version: "3.9"
services:
    app:
        container_name: cryptocademy_app
        restart: always
        image: mats9798/cryptocademy:latest
        depends_on:
            - database
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - cryptocademy_appdata:/var/www/html/storage
        environment:
            APP_ENV: production
            CONTAINER_ROLE: app
    scheduler:
        container_name: cryptocademy_scheduler
        restart: always
        image: mats9798/cryptocademy:latest
        depends_on:
            - database
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - cryptocademy_appdata:/var/www/html/storage
        environment:
            APP_ENV: production
            CONTAINER_ROLE: scheduler
volumes:
    cryptocademy_appdata:
        name: cryptocademy_appdata
networks:
    default:
        name: docker-net
        driver: bridge
