version: "3.9"
services:
    crypto-app:
        container_name: crypto-app
        restart: always
        image: mats9798/cryptocademy:latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - crypto_app_data:/var/www/html/storage
        ports:
            - 80:80
            - 443:443
        networks:
            crypto-net:

    crypto-app_db:
        container_name: crypto-app_db
        image: mysql:8
        restart: always
        networks:
            crypto-net:
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cryptocademy
            MYSQL_USER: cryptocademy
            MYSQL_PASSWORD: cryptocademy
        volumes:
            - crypto_mysql_data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - crypto-app_db
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - PMA_ABSOLUTE_URI=http://pma.developer.local
            - PMA_HOST=crypto-app_db
            - PMA_VERBOSE=CryptoAcademy
            - UPLOAD_LIMIT=2500M
        networks:
            crypto-net:
        ports:
            - 8080:80
volumes:
    crypto_mysql_data:
        name: crypto_mysql_data
    crypto_app_data:
        name: crypto_app_data

networks:
    crypto-net:
        name: crypto-net
        driver: bridge
