#!/bin/bash
echo_and_run() {
  echo "$*"
  "$@"
}
DOCKER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# Restart Container
echo_and_run docker-compose -f $DOCKER_DIR/docker-compose.yml down
echo_and_run docker-compose -f $DOCKER_DIR/docker-compose.yml pull
echo_and_run docker-compose -f $DOCKER_DIR/docker-compose.yml up -d --force-recreate
# Copy Configuration File Into Container
echo_and_run docker cp laravel.env app:/var/www/html/.env
echo_and_run docker cp laravel.env scheduler:/var/www/html/.env
# Optimizing Configuration loading
echo_and_run docker exec app php artisan optimize
echo_and_run docker exec php artisan optimize
# Migrations
echo_and_run docker exec app php artisan migrate --force
# Housekeeping
echo_and_run docker image prune -af
echo_and_run docker system prune -af --volumes

###init
## docker run --rm -v "${PWD}/data/mailserver/config/:/tmp/docker-mailserver/" docker.io/mailserver/docker-mailserver setup email add app@cryptocademy.app LUfBdixKYX5tma39xy7yJWn
#root@cryptocademy:~/app# ls -la data/mailserver/config/
