name: Build BaseImage of CryptoCademy

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u cryptocademy -p ${{ secrets.PRIVATE_REGISTRY_PASSWORD }} registry.cryptocademy.app
        docker build ./docker/build/ -t registry.cryptocademy.app/laravel8-php-8-apache:latest
        docker push registry.cryptocademy.app/laravel8-php-8-apache:latest
