name: Build and Push Docker Image CI

on:
  push:
    branches: [ main,  techstack/github-pipeline ]
  pull_request:
    branches: [ main, techstack/github-pipeline ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Version
      run: |
            docker --version
            node --version
            composer --version
    - name: Composer install
      run: composer install --no-interaction --optimize-autoloader --no-dev
#      run: docker run --rm --interactive --tty -v $(pwd):/app -w /app -u $UID mats9798/crypto-app:latest composer install --no-interaction --optimize-autoloader --no-dev
    - name: Npm install
      run: npm install --production
#      run: docker run --rm --interactive --tty -v $(pwd):/app -w /app node:14 npm install --production
    - name: Build the Docker image
      run: |
            docker build . --file Dockerfile --tag mats9798/crypto-app:latest
            docker login -u mats9798 -p mats9798mats9798
            docker push mats9798/crypto-app:latest

