name: Build and Push Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Version
        run: |
          docker --version
          node --version
          composer --version
      - name: Composer install
        run: composer install --no-interaction --optimize-autoloader --no-dev
      - name: Npm install
        run: npm install --production
      - name: Build the Docker image
        run: |
          DOCKER_IMAGE_NAME="mats9798/crypto-app"
          VERSION_TAG=$GITHUB_REF
          SECOND_TAG="latest"

          docker build --tag=$DOCKER_IMAGE_NAME:$VERSION_TAG .
          docker login -u mats9798 -p mats9798mats9798
          docker push $DOCKER_IMAGE_NAME:$VERSION_TAG
          docker tag $DOCKER_IMAGE_NAME:$VERSION_TAG $DOCKER_IMAGE_NAME:$SECOND_TAG
          docker push $DOCKER_IMAGE_NAME:$SECOND_TAG
