name: Build and Push Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version
        run: |
          docker --version
          node --version
          composer --version
      - name: Composer install
        run: composer install --no-interaction --optimize-autoloader --no-dev
      - name: Npm install
        run: npm install --production
      - name: PHP Artisan
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag mats9798/crypto-app:latest
          docker login -u mats9798 -p mats9798mats9798
          docker push mats9798/crypto-app:latest

